EPI unwarp changes

diff --git a/epi_unwarp b/epi_unwarp
--- a/epi_unwarp
+++ b/epi_unwarp
@@ -1,4 +1,4 @@
-#!/bin/tcsh
+#!/bin/tcsh -f
 #Tyler Blazey, 2011.
 
 #######
@@ -52,10 +52,22 @@ while ($#argv > 0)
 	set flag = $argv[1]; shift;
 	switch ($flag)
 		case -m:
+			if ( ! -e $argv[1] ) then
+				echo "Cannot find image at: $argv[1]"
+				exit 1
+			endif
 			set mag = `$FSLDIR/bin/remove_ext $argv[1]`; shift; breaksw;
 		case -e:
+			if ( ! -e $argv[1] ) then
+				echo "Cannot find image at: $argv[1]"
+				exit 1
+			endif
 			set epi = `$FSLDIR/bin/remove_ext $argv[1]`; shift; breaksw;
 		case -p:
+			if ( ! -e $argv[1] ) then
+				echo "Cannot find image at: $argv[1]"
+				exit 1
+			endif
 			set phase = `$FSLDIR/bin/remove_ext $argv[1]`; shift; breaksw;
 		case -o:
 			set outpath = $argv[1]; shift; breaksw;
@@ -118,6 +130,7 @@ if ($?dir == 0) set dir = "y-"
 if ($?unwrap == 0) set unwrap = 1
 if ($?mask == 0 ) set mask = "--mask=${outroot}mag_brain_mask_to_${outroot}epi_${frame}_brain"
 if ($?epibet == 0 ) set epibet = .2
+set FSL = $FSLDIR/bin
 
 #Check to make sure -reg is set correctly
 set reg_options = ( "smooth" "median" "none" "despike"); echo $reg_options | grep -qw $reg;
@@ -139,72 +152,78 @@ endif
 
 set echo
 #Copy images over
-imcp $mag ${outpath}/${outroot}mag; imcp $epi ${outpath}/${outroot}epi
-imcp $phase ${outpath}/${outroot}phase; 
+$FSL/imcp $mag ${outpath}/${outroot}mag; $FSL/imcp $epi ${outpath}/${outroot}epi
+$FSL/imcp $phase ${outpath}/${outroot}phase
 cd $outpath
 
-#Check to see if the phase map range is as expected
+#Convert field map to radians
 set range = `fslstats ${outroot}phase -R`.
-if ( $range[1] != -4096.000000 || $range[2] != 4092.000000 ) then
+if ( $range[1] == -4096.000000 && $range[2] == 4092.000000 ) then
+	$FSL/fslmaths ${outroot}phase -div 4096 -mul 3.14159265 ${outroot}phase_rad -odt float
+else if ( $range[1] == 0.000000 && $range[2] == 4094.000000 ) then
+	$FSL/fslmaths ${outroot}phase -sub 2047 -div 2047 -mul 3.14159265 ${outroot}phase_rad -odt float		
+else
 	echo "Range of phase map is not -4096.000000 to 4092.000000. Exiting..."
 	exit 1
 endif
 
-#Convert field map to radians
-fslmaths ${outroot}phase -div 4096 -mul 3.14159265 ${outroot}phase
+
 
 #Create brain mask for magnitude
-bet ${outroot}mag ${outroot}mag_brain -m -R
+$FSL/bet ${outroot}mag ${outroot}mag_brain -f 0.4 -m -R
 
 #If user wants, unwrap phase with prelude.
 if ($unwrap == 1) then
-	prelude -p ${outroot}phase -a ${outroot}mag -o ${outroot}phase -m ${outroot}mag_brain_mask
+	$FSL/prelude -p ${outroot}phase_rad -a ${outroot}mag -o ${outroot}phase_rad_unwrap \
+				 -m ${outroot}mag_brain_mask
 endif
 
 #Convert to radians/second
-fslmaths ${outroot}phase -div $delta ${outroot}phase
+$FSL/fslmaths ${outroot}phase_rad_unwrap -div $delta ${outroot}phase_rad_unwrap_secs
 
 ###############
 #Brain Masking#
 ###############
 
 #Extract epi frame, then brain extract
-fslroi ${outroot}epi ${outroot}epi_${frame} $frame 1
-bet ${outroot}epi_${frame} ${outroot}epi_${frame}_brain -m -f $epibet -R
+$FSL/fslroi ${outroot}epi ${outroot}epi_${frame} $frame 1
+$FSL/bet ${outroot}epi_${frame} ${outroot}epi_${frame}_brain -m -f $epibet -R
 
 #Create inverted field map brain mask
-fslmaths ${outroot}phase -abs -bin -mas ${outroot}mag_brain_mask -mul -1 -add 1 -bin \
-		 ${outroot}phase_inv_brain_mask
+$FSL/fslmaths ${outroot}phase_rad_unwrap_secs -abs -bin -mas ${outroot}mag_brain_mask -mul -1 \
+			  -add 1 -bin ${outroot}phase_rad_unwrap_secs_inv_brain_mask
 		 
 #Cluster inverted brain mask
-cluster -i ${outroot}phase_inv_brain_mask -t 0.5 --no_table \
-		-o ${outroot}phase_inv_brain_mask_clust
+$FSL/cluster -i ${outroot}phase_rad_unwrap_secs_inv_brain_mask -t 0.5 --no_table \
+			 -o ${outroot}phase_rad_unwrap_secs_inv_brain_mask_clust
 		
 #Save intensity of largest cluster 
-set max = `fslstats ${outroot}phase_inv_brain_mask_clust -R | awk '{print $2}'`
+set max = `$FSL/fslstats ${outroot}phase_rad_unwrap_secs_inv_brain_mask_clust -R | awk '{print $2}'`
 #Threshhold the image by max, then invert again. Get a new, tighter brain mask.
-fslmaths ${outroot}phase_inv_brain_mask_clust -thr $max -bin -mul -1 -add 1 -bin \
-		 -mas ${outroot}mag_brain_mask ${outroot}mag_brain_mask
+$FSL/fslmaths ${outroot}phase_rad_unwrap_secs_inv_brain_mask_clust -thr $max -bin -mul -1 -add 1 \
+			  -bin -mas ${outroot}mag_brain_mask ${outroot}mag_brain_mask
 		 
 #Use the new brain mask on the field map
-fslmaths ${outroot}phase -mas ${outroot}mag_brain_mask ${outroot}phase
+$FSL/fslmaths ${outroot}phase_rad_unwrap_secs -mas ${outroot}mag_brain_mask \
+			  ${outroot}phase_rad_unwrap_secs
 
 #Get a 50% brain mask
-set fifty = `fslstats ${outroot}mag_brain -P 98 | awk '{print ( $1 / 2 ) }'`
-fslmaths ${outroot}mag_brain -thr $fifty -bin ${outroot}mag_brain_fifty_mask
+set fifty = `$FSL/fslstats ${outroot}mag_brain -P 98 | awk '{print ( $1 / 2 ) }'`
+$FSL/fslmaths ${outroot}mag_brain -thr $fifty -bin ${outroot}mag_brain_fifty_mask
 
 #Erode the original brain mask
-fslmaths ${outroot}mag_brain_mask -ero ${outroot}mag_brain_mask_eroded
+$FSL/fslmaths ${outroot}mag_brain_mask -ero ${outroot}mag_brain_mask_eroded
 
 #Add eroded and fifty masks
-fslmaths ${outroot}mag_brain_mask_eroded -add ${outroot}mag_brain_fifty_mask -thr 0.5 \
-		 -bin ${outroot}mag_brain_mask
+$FSL/fslmaths ${outroot}mag_brain_mask_eroded -add ${outroot}mag_brain_fifty_mask -thr 0.5 \
+		 	  -bin ${outroot}mag_brain_mask
 		 
 #Mask the field map again
-fslmaths ${outroot}phase -mas ${outroot}mag_brain_mask ${outroot}phase
+$FSL/fslmaths ${outroot}phase_rad_unwrap_secs -mas ${outroot}mag_brain_mask \
+			  ${outroot}phase_rad_unwrap_secs
 
 #Erode brain mask again
-fslmaths ${outroot}mag_brain_mask -ero ${outroot}mag_brain_mask_eroded
+$FSL/fslmaths ${outroot}mag_brain_mask -ero ${outroot}mag_brain_mask_eroded
 
 ###########
 #Filtering#
@@ -213,34 +232,38 @@ fslmaths ${outroot}mag_brain_mask -ero ${outroot}mag_brain_mask_eroded
 #Create filter
 switch ($reg)
 	case "despike":
-		fugue --loadfmap=${outroot}phase --savefmap=${outroot}phase_filter_${reg} \
-		--mask=${outroot}mag_brain_mask --despike --despikethreshold=$dthresh
+		$FSL/fugue --loadfmap=${outroot}phase_rad_unwrap_secs \
+				   --mask=${outroot}mag_brain_mask --despike --despikethreshold=$dthresh \
+				   --savefmap=${outroot}phase_rad_unwrap_secs_filter_${reg}
 		breaksw
 	case "smooth":
-		fugue --loadfmap=${outroot}phase --savefmap=${outroot}phase_filter_${reg}  \
-		--mask=${outroot}mag_brain_mask -s $mm3
+		$FSL/fugue --loadfmap=${outroot}phase_rad_unwrap_secs --mask=${outroot}mag_brain_mask \
+		     	   --savefmap=${outroot}phase_rad_unwrap_secs_filter_${reg}-s $mm3
 		breaksw
 	case "median":
-		fugue --loadfmap=${outroot}phase --savefmap=${outroot}phase_filter_${reg}  \
-		--mask=${outroot}mag_brain_mask -m
+		$FSL/fugue --loadfmap=${outroot}phase_rad_unwrap_secs --mask=${outroot}mag_brain_mask -m \
+		           --savefmap=${outroot}phase_rad_unwrap_secs_filter_${reg} 
 		breaksw
 	case "none":
-		imcp ${outroot}phase ${outroot}phase_filter_${reg} 
+		$FSL/imcp ${outroot}phase_rad_unwrap_secs ${outroot}phase_rad_unwrap_secs_filter_${reg} 
 endsw
 
 #Apply the filter to brain edges
-fslmaths ${outroot}phase_filter_${reg}  -sub ${outroot}phase -mas ${outroot}mag_brain_mask_eroded \
-		 -add ${outroot}phase ${outroot}phase
+$FSL/fslmaths ${outroot}phase_rad_unwrap_secs_filter_${reg} -sub ${outroot}phase_rad_unwrap_secs \
+			  -mas ${outroot}mag_brain_mask_eroded -add \
+			  ${outroot}phase_rad_unwrap_secs ${outroot}phase_rad_unwrap_secs
 
 #Shift median to 0
-set median = `fslstats ${outroot}phase -k ${outroot}mag_brain_mask -P 50`
-fslmaths ${outroot}phase -sub $median ${outroot}phase
+set median = `$FSL/fslstats ${outroot}phase_rad_unwrap_secs -k ${outroot}mag_brain_mask -P 50`
+$FSL/fslmaths ${outroot}phase_rad_unwrap_secs -sub $median ${outroot}phase_rad_unwrap_secs
 
 #Estimate signal loss from fieldmap. Range goes from 0 (no signal) to 1 (full signal)
-sigloss -i ${outroot}phase --te=${te} -m ${outroot}mag_brain_mask -s ${outroot}signal_loss
+$FSL/sigloss -i ${outroot}phase_rad_unwrap_secs --te=${te} -m ${outroot}mag_brain_mask \
+			 -s ${outroot}signal_loss
 
 #Multiply mag brain by signal loss image. Will result in a mag brain with areas of signal loss.
-fslmaths ${outroot}signal_loss -mul ${outroot}mag_brain ${outroot}mag_brain_signal_lossed -odt float
+$FSL/fslmaths ${outroot}signal_loss -mul ${outroot}mag_brain ${outroot}mag_brain_signal_lossed \
+			  -odt float
 
 #####################################
 #FUGUE, Registration, Transformation#
@@ -248,39 +271,40 @@ fslmaths ${outroot}signal_loss -mul ${outroot}mag_brain ${outroot}mag_brain_sign
 
 #Run fugue on the signal lossed magnitude image. Will distort it according to the field map. 
 #Then do the same thing for the signal_loss fmap image.
-fugue -i ${outroot}mag_brain_signal_lossed --loadfmap=${outroot}phase \
+$FSL/fugue -i ${outroot}mag_brain_signal_lossed --loadfmap=${outroot}phase_rad_unwrap_secs \
 	  --mask=${outroot}mag_brain_mask -w ${outroot}mag_brain_signal_lossed_distorted \
 	  --nokspace --unwarpdir=$dir --dwell=$dwell 
-fugue -i ${outroot}signal_loss --loadfmap=${outroot}phase --mask=${outroot}mag_brain_mask \
-	  --dwell=$dwell -w ${outroot}signal_loss_distorted --nokspace --unwarpdir=$dir
+$FSL/fugue -i ${outroot}signal_loss --loadfmap=${outroot}phase_rad_unwrap_secs  --dwell=$dwell \
+	  	   -w ${outroot}signal_loss_distorted --nokspace --unwarpdir=$dir \
+	  	   --mask=${outroot}mag_brain_mask
 
 #Threshhold the distorted signal loss brain according to user chosen signal loss threshhold
-fslmaths ${outroot}signal_loss_distorted -thr $thresh ${outroot}signal_loss_distorted
+$FSL/fslmaths ${outroot}signal_loss_distorted -thr $thresh ${outroot}signal_loss_distorted
 
 #Register the distorted magnitude to the distorted functional. Output a transformation file only.
 #Use the threshholded signal loss brain as weighting (areas with 0 will be ignored)
-flirt -in ${outroot}mag_brain_signal_lossed_distorted -ref ${outroot}epi_${frame}_brain \
+$FSL/flirt -in ${outroot}mag_brain_signal_lossed_distorted -ref ${outroot}epi_${frame}_brain \
 	  -omat ${outroot}mag_brain_signal_lossed_distorted_to_${outroot}epi_${frame}_brain.mat -dof 6 \
 	  -inweight ${outroot}signal_loss_distorted
 
 #Apply the created transform to the field map and brain mask
-flirt -in ${outroot}phase -ref ${outroot}epi_${frame}_brain \
+$FSL/flirt -in ${outroot}phase_rad_unwrap_secs -ref ${outroot}epi_${frame}_brain \
 	  -init ${outroot}mag_brain_signal_lossed_distorted_to_${outroot}epi_${frame}_brain.mat \
-	  -applyxfm -out ${outroot}phase_to_${outroot}epi_${frame}_brain
-flirt -in ${outroot}mag_brain_mask -ref ${outroot}epi_${frame}_brain \
+	  -applyxfm -out ${outroot}phase_rad_unwrap_secs_to_${outroot}epi_${frame}_brain
+$FSL/flirt -in ${outroot}mag_brain_mask -ref ${outroot}epi_${frame}_brain \
 	  -init ${outroot}mag_brain_signal_lossed_distorted_to_${outroot}epi_${frame}_brain.mat \
 	  -applyxfm -out ${outroot}mag_brain_mask_to_${outroot}epi_${frame}_brain \
 	  -interp nearestneighbour
 
 #Run fugue using the registerted field map on the distorted epi. 
 #Will undistort the first frame epi and save the shift map that does this.
-fugue --loadfmap=${outroot}phase_to_${outroot}epi_${frame}_brain \
+$FSL/fugue --loadfmap=${outroot}phase_rad_unwrap_secs_to_${outroot}epi_${frame}_brain \
 	  --dwell=$dwell --mask=${outroot}mag_brain_mask_to_${outroot}epi_${frame}_brain \
 	  -i ${outroot}epi_${frame}_brain -u ${outroot}epi_${frame}_brain_undist --unwarpdir=$dir \
 	  --saveshift=${outroot}epi_${frame}_brain_undist_shift
 
 #Convert the shiftwarp to an absolute warp
-convertwarp -s ${outroot}epi_${frame}_brain_undist_shift \
+$FSL/convertwarp -s ${outroot}epi_${frame}_brain_undist_shift \
 		    -o ${outroot}epi_${frame}_brain_undist_shift_warp -r ${outroot}epi_${frame}_brain \
 	        --shiftdir=$dir
 	        
@@ -289,33 +313,37 @@ convertwarp -s ${outroot}epi_${frame}_brain_undist_shift \
 ###################
 
 if ( $?dtimc == 1  || $?boldmc == 1 ) then
-	fslsplit ${outroot}epi ${outroot}epi_tmp
+	$FSL/fslsplit ${outroot}epi ${outroot}epi_tmp
 	foreach tmp ( ${outroot}epi_tmp* )
 		
 		#Create correct pre matrices
 		if ( $?dtimc == 1 ) then
-			set tmp = `remove_ext $tmp`
-			echo $tmp > eddycorrect.log
-			flirt -in $tmp -ref ${outroot}epi_${frame} -nosearch -omat ${tmp}.mat -paddingsize 1 \
-			>> eddycorrect.log
+			set tmp = `$FSL/remove_ext $tmp`
+			echo "processing $tmp" >> eddycorrect.log
+			echo "" >> eddycorrect.log
+			$FSL/flirt -in $tmp -ref ${outroot}epi_${frame} -nosearch -omat ${tmp}.mat \
+						-paddingsize 1
 			set pre = "${tmp}.mat"
+			echo "Final Result:" >> eddycorrect.log
+			cat $pre >> eddycorrect.log
+			echo "" >> eddycorrect.log
 		else
 			if ( $?notfirst == 0 ) then
-				mcflirt -refvol ${frame} -mats -in ${outroot}epi -plots -rmsrel \
-						-rmsabs -out ${outroot}mcf
+				$FSL/mcflirt -refvol ${frame} -mats -in ${outroot}epi -plots -rmsrel \
+							 -rmsabs -out ${outroot}mcf
 			endif
 			set notfirst = 1
-			set tmp = `remove_ext $tmp`
+			set tmp = `$FSL/remove_ext $tmp`
 			set num = `echo $tmp | grep -o "tmp.*[0-9]" | sed 's/tmp//g'`
 			set pre = "${outroot}mcf.mat/MAT_${num}"
 		endif
 
 		#Apply motion correction
-		applywarp -i $tmp -o ${tmp}_undist_mcf -r ${outroot}epi --abs $mask \
-		          -w ${outroot}epi_${frame}_brain_undist_shift_warp --premat=$pre
+		$FSL/applywarp -i $tmp -o ${tmp}_undist_mcf -r ${outroot}epi --abs $mask \
+		          	   -w ${outroot}epi_${frame}_brain_undist_shift_warp --premat=$pre
 	end
 	
-	fslmerge -t ${outroot}undist_mcf ${outroot}epi_tmp*_undist_mcf.nii.gz
+	$FSL/fslmerge -t ${outroot}undist_mcf ${outroot}epi_tmp*_undist_mcf.nii.gz
 	rm ${outroot}epi_tmp*	
 endif
 		
